In [1]:
import pandas as pd

In [2]:
pd.read_csv('dados.csv', sep = ';')

,N�vel,Espessura,TOC(%),TN(%),C/N(%),??13C (�),??15N (�),TS [wt%],U?auth [ppm],U/Th,...,Cu?(EF),Pb?(EF),Zn(EF),Ni?(EF),Cr?(EF),P?(EF),Si?(EF),Ti?(EF),K?(EF),Fe?(EF
0,4D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4A,10,"11,36","0,43","26,42","-26,2","9,1","4,54","18,87","2,06",...,"2,18","35,2","157,33","3,11","3,24","3,85","1,01","0,76","1,14","1,3"
4,3D,15,"11,59","0,46","25,2","-26,5","10,1","3,98","18,8","1,98",...,"1,32","50,21","151,72","2,25","4,44","1,57","1,02","0,73","1,1","1,22"
5,3C,8,"11,13","0,44","25,3","-26,6","8,5","3,67","16,9","1,82",...,"1,25","47,08","160,49","2,34","3,18","3,45","1,09","0,81","1,18","1,23"
6,3B,14,"11,61","0,43",27,"-26,5",9,"2,62","17,47","1,81",...,"0,74","38,5","77,6","2,27","3,17","4,61","1,09","0,82","1,18","0,97"
7,3A,"4,5","11,89","0,54","22,02",-27,"9,8","2,73","16,07","1,66",...,"0,45","71,19","48,36","2,2","3,19","3,47","1,08","0,83","1,26","1,42"
8,2D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2B,8,"8,56","0,32","26,75","-26,2","8,8","1,73","12,8","1,35",...,"0,25","30,93","21,15","1,84","1,88","1,42","1,07","0,77","1,26","1,04"
11,2A,"5,5","7,13","0,29","24,59","-26,6","9,4","1,96","12,07","1,28",...,"0,13","31,99","9,99","2,26","1,93","3,95","1,11","0,79","1,28","1,23"
12,1D,6,"5,53","0,18","30,72","-25,9","10,1","1,72","9,23","1,11",...,"0,17","29,37","20,37","3,51","1,35","1,52","1,28","0,84","1,28","1,08"
13,1C,4,"7,18","0,26","27,62","-26,5","10,5","1,24","10,8","1,17",...,"0,09","21,94","14,36","3,12","1,5","1,27","1,15","0,81","1,29","0,92"
14,1B,"1,5","11,89","0,52","22,87","-27,7","14,8","1,71","13,8","1,51",...,"0,24","38,89","26,95","4,52","2,46","1,68","1,21","0,86","1,24","1,08"
15,1A,"2,5","12,42","0,54",23,"-27,1","17,4","1,49","13,57","1,48",...,"0,57","33,38","61,76","4,6","2,51","1,44","1,24","0,91","1,24","0,99"
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,N�vel,Espessura,NaN,N�vel,TOC(%),NaN,N�vel,Al/(Al + Fe + Mn),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,4D,0,NaN,4D,"8,56",NaN,4D,"0,64",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,4C,0,NaN,4C,"9,15",NaN,4C,"0,64",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,4B,0,NaN,4B,"10,68",NaN,4B,"0,61",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,4A,10,NaN,4A,"11,36",NaN,4A,"0,6",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,3D,15,NaN,3D,"11,59",NaN,3D,"0,62",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,3C,8,NaN,3C,"11,13",NaN,3C,"0,62",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,3B,14,NaN,3B,"11,61",NaN,3B,"0,67",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,3A,"4,5",NaN,3A,"11,89",NaN,3A,"0,58",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2D,0,NaN,2D,"8,56",NaN,2D,"0,6",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2C,0,NaN,2C,"9,15",NaN,2C,"0,62",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2B,8,NaN,2B,"8,56",NaN,2B,"0,65",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2A,"5,5",NaN,2A,"7,13",NaN,2A,"0,62",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,1D,6,NaN,1D,"5,53",NaN,1D,"0,64",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,1C,4,NaN,1C,"7,18",NaN,1C,"0,68",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,1B,"1,5",NaN,1B,"11,89",NaN,1B,"0,65",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,1A,"2,5",NaN,1A,"12,42",NaN,1A,"0,67",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
dados = pd.read_csv('dados.csv', sep = ';')
dados

,N�vel,Espessura,TOC(%),TN(%),C/N(%),??13C (�),??15N (�),TS [wt%],U?auth [ppm],U/Th,...,Cu?(EF),Pb?(EF),Zn(EF),Ni?(EF),Cr?(EF),P?(EF),Si?(EF),Ti?(EF),K?(EF),Fe?(EF
0,4D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4A,10,"11,36","0,43","26,42","-26,2","9,1","4,54","18,87","2,06",...,"2,18","35,2","157,33","3,11","3,24","3,85","1,01","0,76","1,14","1,3"
4,3D,15,"11,59","0,46","25,2","-26,5","10,1","3,98","18,8","1,98",...,"1,32","50,21","151,72","2,25","4,44","1,57","1,02","0,73","1,1","1,22"
5,3C,8,"11,13","0,44","25,3","-26,6","8,5","3,67","16,9","1,82",...,"1,25","47,08","160,49","2,34","3,18","3,45","1,09","0,81","1,18","1,23"
6,3B,14,"11,61","0,43",27,"-26,5",9,"2,62","17,47","1,81",...,"0,74","38,5","77,6","2,27","3,17","4,61","1,09","0,82","1,18","0,97"
7,3A,"4,5","11,89","0,54","22,02",-27,"9,8","2,73","16,07","1,66",...,"0,45","71,19","48,36","2,2","3,19","3,47","1,08","0,83","1,26","1,42"
8,2D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2B,8,"8,56","0,32","26,75","-26,2","8,8","1,73","12,8","1,35",...,"0,25","30,93","21,15","1,84","1,88","1,42","1,07","0,77","1,26","1,04"
11,2A,"5,5","7,13","0,29","24,59","-26,6","9,4","1,96","12,07","1,28",...,"0,13","31,99","9,99","2,26","1,93","3,95","1,11","0,79","1,28","1,23"
12,1D,6,"5,53","0,18","30,72","-25,9","10,1","1,72","9,23","1,11",...,"0,17","29,37","20,37","3,51","1,35","1,52","1,28","0,84","1,28","1,08"
13,1C,4,"7,18","0,26","27,62","-26,5","10,5","1,24","10,8","1,17",...,"0,09","21,94","14,36","3,12","1,5","1,27","1,15","0,81","1,29","0,92"
14,1B,"1,5","11,89","0,52","22,87","-27,7","14,8","1,71","13,8","1,51",...,"0,24","38,89","26,95","4,52","2,46","1,68","1,21","0,86","1,24","1,08"
15,1A,"2,5","12,42","0,54",23,"-27,1","17,4","1,49","13,57","1,48",...,"0,57","33,38","61,76","4,6","2,51","1,44","1,24","0,91","1,24","0,99"
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,N�vel,Espessura,NaN,N�vel,TOC(%),NaN,N�vel,Al/(Al + Fe + Mn),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,4D,0,NaN,4D,"8,56",NaN,4D,"0,64",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,4C,0,NaN,4C,"9,15",NaN,4C,"0,64",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,4B,0,NaN,4B,"10,68",NaN,4B,"0,61",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,4A,10,NaN,4A,"11,36",NaN,4A,"0,6",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,3D,15,NaN,3D,"11,59",NaN,3D,"0,62",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,3C,8,NaN,3C,"11,13",NaN,3C,"0,62",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,3B,14,NaN,3B,"11,61",NaN,3B,"0,67",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,3A,"4,5",NaN,3A,"11,89",NaN,3A,"0,58",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2D,0,NaN,2D,"8,56",NaN,2D,"0,6",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2C,0,NaN,2C,"9,15",NaN,2C,"0,62",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2B,8,NaN,2B,"8,56",NaN,2B,"0,65",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2A,"5,5",NaN,2A,"7,13",NaN,2A,"0,62",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,1D,6,NaN,1D,"5,53",NaN,1D,"0,64",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,1C,4,NaN,1C,"7,18",NaN,1C,"0,68",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,1B,"1,5",NaN,1B,"11,89",NaN,1B,"0,65",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,1A,"2,5",NaN,1A,"12,42",NaN,1A,"0,67",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
type(dados)

pandas.core.frame.DataFrame

In [5]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 37 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   N�vel                33 non-null     object
 1   Espessura            28 non-null     object
 2   TOC(%)               11 non-null     object
 3   TN(%)                28 non-null     object
 4   C/N(%)               28 non-null     object
 5   ??13C (�)            11 non-null     object
 6   ??15N (�)            28 non-null     object
 7   TS [wt%]             28 non-null     object
 8   U?auth [ppm]         11 non-null     object
 9   U/Th                 11 non-null     object
 10  C?org/P              11 non-null     object
 11   Al/(Al + Fe + Mn)   11 non-null     object
 12  Fe/Ti                11 non-null     object
 13  K/Al                 11 non-null     object
 14  Ti/Al                11 non-null     object
 15  Zr/Al ? 10?4         11 non-null     object
 16   Zr/Rb               11 non-null     object
 17   Al?2O?3/TiO?2       11 non-null     object
 18   Si/Al               11 non-null     object
 19  Ba?(EF)              28 non-null     object
 20   Co?(EF)             28 non-null     object
 21   Sr?(EF)             11 non-null     object
 22  Th?(EF)              11 non-null     object
 23   U?(EF)              11 non-null     object
 24  V?(EF)               11 non-null     object
 25   Zr?(EF)             11 non-null     object
 26  Mo?(EF)              11 non-null     object
 27   Cu?(EF)             11 non-null     object
 28   Pb?(EF)             11 non-null     object
 29   Zn(EF)              11 non-null     object
 30   Ni?(EF)             11 non-null     object
 31  Cr?(EF)              11 non-null     object
 32  P?(EF)               11 non-null     object
 33  Si?(EF)              11 non-null     object
 34  Ti?(EF)              11 non-null     object
 35  K?(EF)               11 non-null     object
 36   Fe?(EF              11 non-null     object
dtypes: object(37)
memory usage: 10.0+ KB

In [6]:
dados.head(10)

,N�vel,Espessura,TOC(%),TN(%),C/N(%),??13C (�),??15N (�),TS [wt%],U?auth [ppm],U/Th,...,Cu?(EF),Pb?(EF),Zn(EF),Ni?(EF),Cr?(EF),P?(EF),Si?(EF),Ti?(EF),K?(EF),Fe?(EF
0,4D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4A,10,"11,36","0,43","26,42","-26,2","9,1","4,54","18,87","2,06",...,"2,18","35,2","157,33","3,11","3,24","3,85","1,01","0,76","1,14","1,3"
4,3D,15,"11,59","0,46","25,2","-26,5","10,1","3,98","18,8","1,98",...,"1,32","50,21","151,72","2,25","4,44","1,57","1,02","0,73","1,1","1,22"
5,3C,8,"11,13","0,44","25,3","-26,6","8,5","3,67","16,9","1,82",...,"1,25","47,08","160,49","2,34","3,18","3,45","1,09","0,81","1,18","1,23"
6,3B,14,"11,61","0,43",27,"-26,5",9,"2,62","17,47","1,81",...,"0,74","38,5","77,6","2,27","3,17","4,61","1,09","0,82","1,18","0,97"
7,3A,"4,5","11,89","0,54","22,02",-27,"9,8","2,73","16,07","1,66",...,"0,45","71,19","48,36","2,2","3,19","3,47","1,08","0,83","1,26","1,42"
8,2D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
tipos_de_dados = pd.DataFrame(dados.dtypes, columns = ['Tipos de Dados'])

In [8]:
tipos_de_dados.columns.name = 'espessura'

In [9]:
tipos_de_dados

espessura           Tipos de Dados
N�vel                       object
Espessura                   object
TOC(%)                      object
TN(%)                       object
C/N(%)                      object
??13C (�)                   object
??15N (�)                   object
TS [wt%]                    object
U?auth [ppm]                object
U/Th                        object
C?org/P                     object
 Al/(Al + Fe + Mn)          object
Fe/Ti                       object
K/Al                        object
Ti/Al                       object
Zr/Al ? 10?4                object
 Zr/Rb                      object
 Al?2O?3/TiO?2              object
 Si/Al                      object
Ba?(EF)                     object
 Co?(EF)                    object
 Sr?(EF)                    object
Th?(EF)                     object
 U?(EF)                     object
V?(EF)                      object
 Zr?(EF)                    object
Mo?(EF)                     object
 Cu?(EF)                    object
 Pb?(EF)                    object
 Zn(EF)                     object
 Ni?(EF)                    object
Cr?(EF)                     object
P?(EF)                      object
Si?(EF)                     object
Ti?(EF)                     object
K?(EF)                      object
 Fe?(EF                     object

In [10]:
dados.shape

(34, 37)

In [11]:
dados.shape[0]

34

In [12]:
dados.shape[1]

37

In [14]:
print('A base de dados apresenta {} de amostras e {} variáveis'.format(dados.shape[0], dados.shape[1]))

A base de dados apresenta 34 de amostras e 37 variáveis

In [21]:
dados[''].mean()

KeyError: ''